Repository g3w-suite/g3w-client, pull requests merged in 2022-09, with the labels that each got.

#168 Hide editing (pencil) button on result content when editing panel is open
  src/app/gui/queryresults/queryresultsservice.js
Labels: bug

#173 Fix unhandled error on query response when `QGIS Project setting -> Add geometry to feature response` is set to false
  src/app/core/utils/geo.js
  src/app/core/utils/parsers.js
Labels: bug

#187 Fix `TypeError: geometry.getLinearRing is not a function` when measuring a MultiPolygon layer (editing plugin)
  src/app/core/utils/ol.js
Labels: bug

#190 Fix task completion callback called too many times async (`gulp test`)
  gulpfile.js
Labels: tests

#174 Add `src/directives` folder (vue directives refactor)
  src/app/gui/vue/directives/v-disabled.js
  src/app/gui/vue/directives/v-select2.js
  src/app/gui/vue/directives/v-selected-first.js
  src/app/gui/vue/vue.directives.js
  src/app/main.js
  src/directives/utils.js
  src/directives/v-checked.js
  src/directives/v-disabled.js
  src/directives/v-download.js
  src/directives/v-online.js
  src/directives/v-plugins.js
  src/directives/v-select2.js
  src/directives/v-selected-first.js
  src/directives/v-t-html.js
  src/directives/v-t-placeholder.js
  src/directives/v-t-plugin.js
  src/directives/v-t-title.js
  src/directives/v-t-tooltip.js
  src/directives/v-t.js
Labels: refactoring

#175 Delete `src/app/gui/app/index.js`
  src/app/gui/app/index.js
Labels: refactoring

#176 Add `src/mixins` folder (vue mixins refactor)
  src/app/gui/vue/vue.mixins.js
  src/mixins/autocomplete.js
  src/mixins/base-input.js
  src/mixins/fields.js
  src/mixins/form-inputs.js
  src/mixins/geo.js
  src/mixins/index.js
  src/mixins/media.js
  src/mixins/metadata.js
  src/mixins/resize.js
  src/mixins/select.js
  src/mixins/select2.js
  src/mixins/widget.js
Labels: refactoring

#179 Move `"gui/vue/vue.filter"` into `"app/main"`
  src/app/gui/vue/vue.filter.js
  src/app/main.js
Labels: refactoring

#178 Move `"gui/vue/vue.globalcomponents"` into `"app/main"`
  src/app/gui/vue/vue.globalcomponents.js
  src/app/main.js
Labels: refactoring

#180 Move `"gui/vue/vue.vueappplugin"` into `"app/main"`
  src/app/gui/vue/vueappplugin.js
  src/app/main.js
Labels: refactoring

#185 Move `"gui/app/layout"` into `"components/App.vue"`
  src/app/gui/app/layout.js
  src/app/main.js
  src/components/App.vue
Labels: refactoring

#191 Add `PULL_REQUEST_TEMPLATE.md`
  .github/PULL_REQUEST_TEMPLATE.md
Labels: github

#196 Fix unselectable Layer Style containing a special character in name (catalog layers)
  src/components/CatalogLayersLegendItems.vue
Labels: bug

#198 Fire `changeinput` event also on initial default value of input fields
  src/app/gui/inputs/service.js
  src/mixins/base-input.js
Labels: refactoring

#204 Disable resizable text area for multiline editing widget
  src/components/InputTextArea.vue
Labels: ux

#201 Improve labels readability on small sizes (editing panel)
  src/assets/style/less/g3w-form.less
  src/components/GlobalTabsNode.vue
  src/components/InputBase.vue
Labels: ux

#194 Add title icons to `release.yml`
  .github/release.yml
Labels: github

#197 Add `improve_documentation.yml` (issue templates)
  .github/ISSUE_TEMPLATE/improve_documentation.yml
Labels: github

#151 Remove md5 hash for static assets within `index.prod.html`
  gulpfile.js
  src/index.prod.html
Labels: config

#205 Add `src/components/SearchPanelLabel.vue`
  src/components/SearchPanel.vue
  src/components/SearchPanelLabel.vue
Labels: refactoring

#212 Fix disabled `"Add WMS Layers Panel"` after editing projection on current selected layer
  src/components/WMSLayersPanel.vue
Labels: bug

#215 Add new search URL parameter `<url>?ztf=<LAYER_ORIGNAME>` (zoom to layer features)
  src/app/gui/map/mapservice.js
Labels: feature

#218 Fix `TypeError: layer.getGeometryType is not a function` when parsing a table layer response (alphanumeric layer)
  src/app/core/utils/parsers.js
Labels: bug

#220 Split and refactor `Map.vue` into multiple components (MapFooter, MapFooterRight, MapFooterLeft)
  src/components/Map.vue
  src/components/MapFooter.vue
  src/components/MapFooterLeft.vue
  src/components/MapFooterRight.vue
Labels: refactoring

#219 Split and refactor `SidebarItem.vue` into multiple components (SidebarItemAction)
  src/components/SidebarItem.vue
  src/components/SidebarItemAction.vue
Labels: refactoring

#213 Split and refactor `Catalog.vue` into multiple components (CatalogLayerContextMenu)
  src/components/Catalog.vue
  src/components/CatalogLayerContextMenu.vue
Labels: refactoring

#226 Emit changeinput event only when input value is fill with default value
  src/mixins/base-input.js
Labels: bug

#224 Add more space between items on result query content
  src/components/GlobalTabsNode.vue
Labels: ux
