Repository g3w-suite/g3w-client, pull requests merged in 2022-08, with the labels that each got.

#121 Move `src/config` into `src/app/config`
  .gitignore
  README.md
  config.template.js
  src/app/config.js
  src/app/core/applicationservice.js
  src/app/core/layers/baselayers/binglayer.js
  src/app/dev/index.js
  src/config/README.md
  src/config/index.js
  src/config/keys/index.js
  src/config/keys/index.template.js
  test/specs/application/service.js
Labels: refactoring

#125 fix wrong default vendor keys names within `config.template.js`
  config.template.js
  src/config/keys/index.js
Labels: bug

#126 G3w keys dev index
  src/app/dev/index.js
  src/app/g3w-ol/controls/geocodingcontrol.js
  src/app/g3w-ol/controls/nominatimcontrol.js
  src/app/gui/map/control/factory.js
  src/app/gui/map/mapservice.js
  src/app/gui/vue/vueappplugin.js
Labels: bug

#120 Add `.github/release.yml` (github release notes automation)
  .github/release.yml
Labels: github

#95 Add `src/services` folder (service singletons refactor)
  src/app/core/apiservice.js
  src/app/core/applicationservice.js
  src/app/core/clipboardservice.js
  src/app/core/data/expression/service.js
  src/app/core/data/ows/service.js
  src/app/core/data/proxy/service.js
  src/app/core/data/query/service.js
  src/app/core/data/routerservice.js
  src/app/core/data/search/service.js
  src/app/core/editing/changesmanager.js
  src/app/core/history_router.js
  src/app/core/iframe/routerservice.js
  src/app/core/iframe/services/app/service.js
  src/app/core/iframe/services/plugins/editing/service.js
  src/app/core/relations/relationsservice.js
  src/app/core/router.js
  src/app/core/task/service.js
  src/app/core/workflow/workflowsstack.js
  src/app/gui/gui.js
  src/app/gui/querybuilder/service.js
  src/services/api.js
  src/services/application.js
  src/services/clipboard.js
  src/services/data-expression.js
  src/services/data-ows.js
  src/services/data-proxy.js
  src/services/data-query.js
  src/services/data-search.js
  src/services/data.js
  src/services/editing.js
  src/services/gui.js
  src/services/history.js
  src/services/iframe-app.js
  src/services/iframe-editing.js
  src/services/iframe-plugin.js
  src/services/index.js
  src/services/querybuilder.js
  src/services/relations.js
  src/services/router.js
  src/services/tasks.js
  src/services/workflows.js
Labels: refactoring

#94 Add `src/store` folder (registry singletons refactor)
  src/app/core/catalog/cataloglayersstoresregistry.js
  src/app/core/editing/sessionsregistry.js
  src/app/core/map/maplayersstoresregistry.js
  src/app/core/plugin/pluginsregistry.js
  src/app/core/project/projectsregistry.js
  src/app/gui/component/componentsregistry.js
  src/app/gui/map/control/registry.js
  src/store/catalog-layers.js
  src/store/components.js
  src/store/index.js
  src/store/map-controls.js
  src/store/map-layers.js
  src/store/plugins.js
  src/store/projects.js
  src/store/sessions.js
Labels: refactoring

#97 Remove `src/app/gui/app/index.js`
  src/app/gui/app/index.js
  src/app/main.js
Labels: refactoring

#130 Patch for a circular dependency found between `core/utils/geo.js` and `core/utils/ol.js`
  src/app/core/utils/ol.js
  src/app/g3w-ol/interactions/measureinteraction.js
Labels: bug

#131 Add Geocoding mapcontrol
  src/app/core/utils/parsers.js
  src/app/dev/index.js
  src/app/g3w-ol/controls/geocodingcontrol.js
  src/app/g3w-ol/controls/nominatimcontrol.js
  src/app/gui/map/control/factory.js
  src/app/gui/map/mapservice.js
Labels: feature

#132 Delete `src/app/g3w-ol/interactions/mouseEvents.js`
  src/app/g3w-ol/interactions/mouseEvents.js
Labels: refactoring

#133 Delete `src/app/g3w-ol/utils/utils.js`
  src/app/g3w-ol/utils/utils.js
Labels: refactoring

#134 Move `core/applicationstate` into `store/application-state`
  src/app/core/applicationstate.js
  src/app/core/plugin/pluginservice.js
  src/app/g3w-ol/controls/geocodingcontrol.js
  src/app/gui/map/vue/map.js
  src/app/gui/viewport/viewport.js
  src/app/gui/vue/global-components/datetime.vue
  src/store/application-state.js
Labels: refactoring

#136 Remove `{G3W_VERSION}` placeholder
  gulpfile.js
  src/services/application.js
Labels: refactoring

#138 Fix issue on wrong old dev template.
  gulpfile.js
Labels: bug, config

#139 Add `G3W_ADMIN_PATH` constant within `config.template.js`
  config.template.js
Labels: config

#140 Fix mapcontrols left alignement on mobile when keyboard is open
  src/app/gui/map/mapservice.js
Labels: bug, ux

#141 Change Nominatim label to Nominatim (OSM) on geocoding search result
  src/app/g3w-ol/controls/geocodingcontrol.js
Labels: ux

#142 Update wrong project license within `package.json` (MPL-2.0)
  package.json
Labels: config

#143 Fix `geometryFields` circular dependency found between `core/utils/geo.js` and `core/layers/features/feature.js`
  src/app/core/layers/features/feature.js
Labels: bug

#148 Fix missing variable reference SIDEBARWIDTH on Viewport.vue
  src/components/Viewport.vue
  src/services/viewport.js
Labels: bug

#149 Fix issue on vue-template-compiler using named slot.
  package.json
  src/components/Field.vue
  src/components/FieldText.vue
Labels: bug, dependencies, config

#137 Refactor `gulpfile.js`
  gulpfile.js
  package.json
Labels: config, refactoring

#155 Change default geocoding control marker icon (`yellow circle` --> `red marker`)
  src/app/g3w-ol/controls/geocodingcontrol.js
  src/app/gui/map/mapservice.js
Labels: ux

#157 Prevent parsing of invalid Z values (z = 0) due to a bug on `ol.format.WMSGetFeatureInfo()`
  src/app/core/utils/geo.js
  src/app/core/utils/parsers.js
Labels: bug

#153 Allow to download only filtered layer features and improve selection of layer properties
  src/app/core/layers/geolayermixin.js
  src/app/core/layers/layer.js
  src/app/gui/map/mapservice.js
Labels: ux

#158 Refactor `gulpfile.js` (run-sequence)
  gulpfile.js
  package.json
Labels: config, refactoring

#161 Add map layer with source.type = 'vectortile'
  src/app/core/layers/layer.js
  src/app/core/layers/layerfactory.js
  src/app/core/layers/providers/providersfactory.js
Labels: feature

#163 Let geocoding map control results and marker stay visible on map after click
  src/app/g3w-ol/controls/geocodingcontrol.js
Labels: ux
