Repository g3w-suite/g3w-client, pull requests merged in 2023-11, with the labels that each got.

#515 Fix not empty results for 1:N relations (search widget)
  src/app/core/layers/filter/expression.js
  src/app/gui/search/vue/panel/searchservice.js
Labels: bug

#513 Add search support for `Relation Reference` widget (1:N relations)
  src/app/core/layers/filter/expression.js
  src/app/core/layers/layer.js
  src/app/core/layers/providersfactory.js
  src/app/gui/search/vue/panel/searchservice.js
  src/components/Relation.vue
  src/utils/createSingleFieldParameter.js
Labels: feature

#519 Add support to qgis `'postgresraster'` layer [g3w-admin PR#652]
  src/app/core/layers/layer.js
  src/app/core/layers/layerfactory.js
  src/app/core/layers/providersfactory.js
  src/app/gui/queryresults/queryresultsservice.js
Labels: feature

#363 Prevent tooltips help text from being occasionally clipped by surrounding containers (ref: mouse over hints)
  src/app/gui/map/mapservice.js
  src/assets/style/less/admin-lte2-less/skins/g3w-skin-blue.less
  src/assets/style/less/app.less
  src/assets/style/less/g3w-form.less
  src/assets/style/less/g3w-mapcontrols.less
  src/assets/style/less/g3w-queryresults.less
  src/assets/style/less/g3w-skins/blue/g3w-form.less
  src/assets/style/less/g3w-skins/blue/g3w-mapcontrols.less
  src/assets/style/less/g3w-skins/blue/g3w-queryresults.less
  src/assets/style/less/g3w-skins/blue/g3w-skin.less
  src/assets/style/less/g3w-skins/green/g3w-form.less
  src/assets/style/less/g3w-skins/green/g3w-mapcontrols.less
  src/assets/style/less/g3w-skins/green/g3w-queryresults.less
  src/assets/style/less/g3w-skins/green/g3w-skin.less
  src/assets/style/less/g3w-skins/purple/g3w-form.less
  src/assets/style/less/g3w-skins/purple/g3w-mapcontrols.less
  src/assets/style/less/g3w-skins/purple/g3w-queryresults.less
  src/assets/style/less/g3w-skins/purple/g3w-skin.less
  src/assets/style/less/g3w-skins/red/g3w-form.less
  src/assets/style/less/g3w-skins/red/g3w-mapcontrols.less
  src/assets/style/less/g3w-skins/red/g3w-queryresults.less
  src/assets/style/less/g3w-skins/red/g3w-skin.less
  src/assets/style/less/g3w-skins/yellow/g3w-form.less
  src/assets/style/less/g3w-skins/yellow/g3w-mapcontrols.less
  src/assets/style/less/g3w-skins/yellow/g3w-queryresults.less
  src/assets/style/less/g3w-skins/yellow/g3w-skin.less
  src/components/CatalogLayerContextMenu.vue
  src/components/CatalogTristateTree.vue
  src/components/InputLonLat.vue
  src/components/PrintPage.vue
  src/components/QueryBuilderSearch.vue
  src/components/QueryResultsAction.vue
  src/components/Sidebar.vue
  src/components/TableToolbar.vue
  src/directives/v-t-tooltip.js
Labels: ux

#511 Add new project option: WMS GetMap image format [g3w-admin]
  src/app/core/layers/map/wmslayer.js
  src/app/core/project/project.js
Labels: feature

#525 Check for empty for geocoding providers: `initConfig.group.mapcontrols.geocoding`
  src/components/MapControlGeocoding.vue
Labels: bug
