Repository g3w-suite/g3w-client, pull requests merged in 2023-08, with the labels that each got.

#462 ArcGIS Rest Servers connection
  src/app/core/layers/layerfactory.js
Labels: bug

#468 Search input fields with strictly dependence
  src/app/core/utils/utils.js
Labels: bug

#470 Change atlas field input in accord on change print atlas template
  src/components/Print.vue
  src/components/PrintSelectAtlasFieldValues.vue
Labels: bug

#326 Move `gui/workflow/createUserMessageStepsFactory.js` into `components/UserMessageSteps.js`
  src/app/core/workflow/workflow.js
  src/components/UserMessageSteps.js
  src/components/index.js
Labels: refactoring

#331 Move `components/GlobalBarLoader.js` into `components/GlobalBarLoader.vue`
  src/components/Form.vue
  src/components/GlobalBarLoader.js
  src/components/GlobalBarLoader.vue
  src/components/GlobalProgressBar.js
  src/components/GlobalProgressBar.vue
  src/components/InputBase.vue
  src/components/InputMedia.vue
  src/components/MapAddLayer.vue
  src/components/NotifyDownload.vue
  src/components/NotifyPlugins.vue
  src/components/PrintPage.vue
  src/components/QueryBuilder.vue
  src/components/QueryBuilderSearch.vue
  src/components/QueryResults.vue
  src/components/Tool.vue
  src/components/Tools.vue
  src/components/Viewport.vue
  src/components/WMS.vue
  src/components/index.js
  src/index.prod.js
Labels: refactoring

#329 Add `src/components/MapControlButton.js`
  src/app/g3w-ol/controls/control.js
  src/components/MapControlButton.js
  src/components/index.js
Labels: refactoring

#314 Remove yeoman dependency (ref: `"generator-browserify"` and `"generator-karma"`)
  package.json
Labels: dependencies

#365 Remove `"regenerator-runtime"` polyfill
  .babelrc
  package.json
Labels: dependencies

#251 Remove `"http-proxy"` dependency from package.json
  package.json
Labels: dependencies

#311 Install `lodash.clonedeep` package
  package.json
  src/app/core/layers/features/featuresstore.js
  src/app/core/layers/tablelayer.js
  src/app/gui/component/component.js
  src/services/application.js
Labels: dependencies

#474 Improves Swedish translation
  src/locales/se.js
Labels: i18n

#452 Install `util-deprecate` package
  gulpfile.js
  package.json
  src/deprecated.js
  src/index.prod.js
Labels: dependencies

#457 Delete folder `src/app/core/layers/map/baselayers/`
  src/app/core/layers/map/baselayers/binglayer.js
  src/app/core/layers/map/baselayers/osmlayer.js
Labels: refactoring

#459 Move `"g3w-ol/g3w.ol"` into `"gui/map/mapservice"`
  src/app/g3w-ol/g3w.ol.js
  src/app/g3w-ol/map/maphelpers.js
  src/app/gui/map/mapservice.js
Labels: refactoring

#456 Refactor function `ProviderFactory::get(providerType, serverType, sourceType)`
  src/app/core/layers/layer.js
  src/app/core/layers/providers/geojsonprovider.js
  src/app/core/layers/providers/kmlprovider.js
  src/app/core/layers/providers/provider.js
  src/app/core/layers/providers/providersfactory.js
  src/app/core/layers/providers/qgisprovider.js
  src/app/core/layers/providers/wfsprovider.js
  src/app/core/layers/providers/wmsprovider.js
  src/app/core/layers/providers/xmlprovider.js
  src/app/core/layers/providersfactory.js
  src/app/gui/map/mapservice.js
Labels: refactoring

#476 Prevent hiding printing controls for map layers having source `external: false` (ref: `"geoscreenshot"` and `"screenshot"` map controls)
  src/app/g3w-ol/controls/screenshotcontrol.js
Labels: bug

#317 Refactor `app/gui/queryresults/queryresultsservice.js`
  src/app/g3w-ol/controls/querybydrawpolygoncontrol.js
  src/app/g3w-ol/controls/querycontrol.js
  src/app/gui/queryresults/queryresultsservice.js
  src/index.prod.js
  src/services/data-query.js
  src/services/gui.js
  src/store/plugins.js
Labels: refactoring

#449 Refactor function `LayerFactory::get(config = {})`
  src/app/core/layers/baselayer.js
  src/app/core/layers/baselayers/arcgislayer.js
  src/app/core/layers/baselayers/baselayers.js
  src/app/core/layers/baselayers/binglayer.js
  src/app/core/layers/baselayers/osmlayer.js
  src/app/core/layers/baselayers/tmslayer.js
  src/app/core/layers/baselayers/wmslayer.js
  src/app/core/layers/baselayers/wmtslayer.js
  src/app/core/layers/layerfactory.js
Labels: refactoring

#455 Delete folder `src/app/core/layers/legend/` (internal helpers refactor)
  src/app/core/layers/imagelayer.js
  src/app/core/layers/legend/arcgismapserverlegend.js
  src/app/core/layers/legend/legendservice.js
  src/app/core/layers/legend/wmslegend.js
  src/app/core/utils/geo.js
  src/components/CatalogLayerLegend.vue
  src/components/CatalogLayersLegend.vue
Labels: refactoring

#454 Delete folder `src/app/core/expression/` (internal helpers refactor)
  src/app/api.js
  src/app/core/expression/inputservice.js
  src/app/core/expression/tabservice.js
  src/app/gui/form/formservice.js
  src/components/GlobalTabs.vue
Labels: refactoring

#478 Reproject query geometries when project layers have a different CRS (ref: `"querybbox"`, `"querybypolygon"` and `"querybydrawpolygon"` controls)
  src/app/core/utils/geo.js
Labels: bug
