Repository g3w-suite/g3w-client, pull requests merged in 2023-10, with the labels that each got.

#495 Prevent datetimepicker widget from being occasionally clipped by surrounding container (editing mode)
  src/components/InputDateTimePicker.vue
Labels: ux

#489 Delete `src/app/core/errors/parser/errorparser.js`
  src/app/core/errors/parser/errorparser.js
Labels: refactoring

#483 Add support to editable vector joins (1:1 relations)
  src/app/constant.js
  src/app/core/editing/editor.js
  src/app/core/editing/session.js
  src/app/core/layers/features/featuresstore.js
  src/app/core/layers/layer.js
  src/app/core/layers/tablelayer.js
  src/app/core/relations/relation.js
  src/app/core/relations/relations.js
  src/app/core/workflow/step.js
  src/app/core/workflow/workflow.js
  src/app/gui/table/tableservice.js
  src/assets/style/less/g3w-overwrite-extenal.less
  src/assets/style/less/g3w-skins/blue/g3w-editing-panel.less
  src/assets/style/less/g3w-skins/green/g3w-editing-panel.less
  src/assets/style/less/g3w-skins/purple/g3w-editing-panel.less
  src/assets/style/less/g3w-skins/red/g3w-editing-panel.less
  src/assets/style/less/g3w-skins/yellow/g3w-editing-panel.less
  src/locales/it.js
  src/services/data-search.js
Labels: feature

#499 Modal preview image gets cropped on small screens
  src/assets/style/less/admin-lte2-less/sidebar.less
  src/assets/style/less/g3w-sidebar.less
  src/components/FieldImage.vue
  src/components/GlobalImage.vue
  src/components/GlobalTabsNode.vue
  src/components/QueryResults.vue
  src/components/Relations.vue
  src/components/Sidebar.vue
Labels: bug

#504 Various fixes related to value relation fields (query builder, editing mode, bbox cache, ..)
  src/app/core/editing/editor.js
  src/app/core/editing/session.js
  src/app/core/layers/features/feature.js
  src/app/core/layers/tablelayer.js
  src/app/core/relations/relation.js
  src/app/core/utils/utils.js
  src/app/gui/queryresults/queryresultsservice.js
  src/app/gui/search/vue/panel/searchservice.js
  src/assets/style/less/g3w-sidebar.less
Labels: bug

#510 Ensure WMS project layer's legend item is highlighted after clicking on it (click to select)
  src/app/gui/queryresults/queryresultsservice.js
  src/components/CatalogTristateTree.vue
Labels: bug

#503 Allow to store layer's expression filters into project (authenticathed users)
  src/app/core/layers/imagelayer.js
  src/app/core/layers/layer.js
  src/app/core/layers/mixins/download.js
  src/app/core/layers/mixins/geo.js
  src/app/core/layers/mixins/relations.js
  src/app/core/layers/mixins/selection.js
  src/app/core/layers/providersfactory.js
  src/app/core/layers/tablelayer.js
  src/app/core/layers/utils/QgsFilterToken.js
  src/app/core/layers/utils/addToSelection.js
  src/app/core/layers/utils/removeFromSelection.js
  src/app/core/layers/vectorlayer.js
  src/app/gui/map/mapservice.js
  src/app/gui/queryresults/queryresultsservice.js
  src/app/gui/table/tableservice.js
  src/assets/style/less/g3w-catalog.less
  src/assets/style/less/g3w-overwrite-extenal.less
  src/components/Catalog.vue
  src/components/CatalogLayerContextMenu.vue
  src/components/CatalogTristateTree.vue
  src/components/GlobalBarLoader.vue
  src/components/GlobalProgressBar.vue
  src/components/MapControlButton.js
  src/components/MapControlGeocoding.js
  src/components/QueryResults.vue
  src/components/Sidebar.vue
  src/components/Table.vue
  src/components/TableBody.vue
  src/components/TableSelectRow.vue
  src/components/TableToolbar.vue
  src/locales/de.js
  src/locales/en.js
  src/locales/fi.js
  src/locales/fr.js
  src/locales/it.js
  src/locales/ro.js
  src/locales/se.js
  src/utils/prompt.js
Labels: feature
