Repository g3w-suite/g3w-client, pull requests merged in 2023-09, with the labels that each got.

#482 Strick check `undefined !== filter` for attributes within `QGISProvider::getFeatures()` (editing plugin)
  src/app/core/layers/providersfactory.js
Labels: bug

#479 Add `jsconfig.json`
  jsconfig.json
Labels: config

#159 Add support for multi fields relations
  src/app/core/editing/editor.js
  src/app/core/editing/session.js
  src/app/core/layers/tablelayer.js
  src/app/core/relations/relation.js
  src/app/core/relations/relations.js
  src/app/g3w-ol/controls/geocodingcontrol.js
  src/app/gui/table/tableservice.js
  src/components/Sidebar.vue
Labels: feature
