Repository g3w-suite/g3w-client, pull requests merged in 2023-03, with the labels that each got.

#356 Include external layers into `querybypolygon` search results (ref: `addlayers` map control )
  src/app/core/data/service.js
  src/app/core/utils/geo.js
  src/app/g3w-ol/controls/interactioncontrol.js
  src/app/g3w-ol/controls/querybypolygoncontrol.js
  src/app/gui/catalog/catalogservice.js
  src/app/gui/map/mapservice.js
  src/app/gui/queryresults/queryresultsservice.js
  src/components/Catalog.vue
  src/components/CatalogTristateTree.vue
  src/components/MapAddLayer.vue
  src/components/QueryResults.vue
  src/locales/de.js
  src/locales/en.js
  src/locales/fi.js
  src/locales/fr.js
  src/locales/it.js
  src/locales/ro.js
  src/locales/se.js
  src/services/data-query.js
Labels: ux

#367 Fallback to default widget value for `InputRange.vue` (optional + empty fields)
  src/components/InputRange.vue
Labels: ux

#369 Fix undefined property `queryResponse.query.external` after setting a new query response (ref: editing plugin)
  src/app/gui/queryresults/queryresultsservice.js
Labels: bug

#309 Add new npm / glup tasks: `clone:default_plugins`, `build:dev_plugins`, `watch:plugins`
  README.md
  gulpfile.js
  package.json
Labels: docs, config

#364 Prevent hamburger menu hiding on small screens (ref: viewport width < 768 px)
  src/app/g3w-ol/controls/geocodingcontrol.js
  src/assets/style/less/admin-lte2-less/header.less
  src/assets/style/less/app.less
  src/assets/style/less/g3w-header.less
  src/assets/style/less/g3w-mapcontrols.less
  src/assets/style/less/g3w-sidebar.less
  src/components/App.vue
  src/components/Sidebar.vue
Labels: bug

#325 Add `src/index.dev.js` and `src/index.dev.js` (app entrypoints)
  config.template.js
  gulpfile.js
  src/app/api.js
  src/app/constant.js
  src/app/dev/index.js
  src/assets/vendors/index.css.html
  src/assets/vendors/index.js.html
  src/deprecated.js
  src/globals.js
  src/index.dev.js
  src/index.prod.js
Labels: docs, config, refactoring

#380 Show Legend image on WMS external layer on TOC
  src/components/CatalogLayerLegend.vue
Labels: bug

#341 Add new map control `querybydrawpolygon`
  src/app/core/layers/layersstore.js
  src/app/g3w-ol/controls/basequerypolygoncontrol.js
  src/app/g3w-ol/controls/control.js
  src/app/g3w-ol/controls/interactioncontrol.js
  src/app/g3w-ol/controls/measurecontrol.js
  src/app/g3w-ol/controls/querybboxcontrol.js
  src/app/g3w-ol/controls/querybydrawpolygoncontrol.js
  src/app/g3w-ol/controls/querybypolygoncontrol.js
  src/app/g3w-ol/controls/querycontrol.js
  src/app/g3w-ol/controls/scalecontrol.js
  src/app/gui/map/control/factory.js
  src/app/gui/map/mapservice.js
  src/app/gui/queryresults/queryresultsservice.js
  src/components/CatalogTristateTree.vue
  src/components/QueryResults.vue
  src/locales/de.js
  src/locales/en.js
  src/locales/fi.js
  src/locales/fr.js
  src/locales/it.js
  src/locales/ro.js
  src/locales/se.js
  src/services/data-query.js
  src/store/map-controls.js
Labels: feature

#382 Send FORMAT on wms layer if set on source format property
  src/app/core/layers/map/wmslayer.js
  src/app/g3w-ol/layers/rasters.js
  src/app/gui/map/mapservice.js
  src/components/CatalogLayerLegend.vue
Labels: bug

#378 Add support for single category layer legend items (ref: missing category and title)
  src/app/core/layers/geolayermixin.js
  src/components/CatalogLayerLegend.vue
Labels: bug

#385 Fix english word mispelling within metadata tab (ref: "References")
  src/locales/en.js
Labels: i18n

#374 Show Feature Count for legend items
  src/app/core/layers/layer.js
  src/app/core/layers/layersstore.js
  src/app/core/project/project.js
  src/components/CatalogLayerLegend.vue
  src/components/CatalogTristateTree.vue
Labels: feature

#384 Hide Project bookmarks section when no bookmarks is set on QGIS Project (ref: left sidebar menu items)
  src/components/SpatialBookMarks.vue
Labels: feature

#388 Add new map control `zoomhistory`
  src/app/constant.js
  src/app/g3w-ol/controls/zoomhistorycontrol.js
  src/app/gui/map/control/factory.js
  src/app/gui/map/mapservice.js
  src/components/Map.vue
  src/components/MapControlZoomHistory.vue
  src/components/index.js
  src/locales/de.js
  src/locales/en.js
  src/locales/fi.js
  src/locales/fr.js
  src/locales/it.js
  src/locales/ro.js
  src/locales/se.js
Labels: feature

#389 Fill editing `default_expression` input field with computed default value (eg. `$area`)
  src/app/core/expression/inputservice.js
  src/app/core/layers/tablelayer.js
  src/app/gui/form/formservice.js
  src/app/gui/inputs/input.js
  src/app/gui/inputs/service.js
  src/app/gui/queryresults/queryresultsservice.js
  src/components/InputDateTimePicker.vue
  src/components/QueryResults.vue
  src/locales/de.js
  src/locales/en.js
  src/locales/fi.js
  src/locales/fr.js
  src/locales/it.js
  src/locales/ro.js
  src/locales/se.js
  src/services/data-expression.js
  src/services/data.js
  src/services/history.js
  src/services/index.js
Labels: bug
