Repository g3w-suite/g3w-client, pull requests merged in 2023-01, with the labels that each got.

#281 Add breadcrumb to form component
  src/app/api.js
  src/app/constant.js
  src/app/core/layers/legend/wmslegend.js
  src/app/gui/form/formservice.js
  src/app/gui/queryresults/queryresultsservice.js
  src/app/gui/relations/vue/relationspage.js
  src/app/gui/viewport/contentsviewer.js
  src/app/main.js
  src/assets/style/less/app.less
  src/assets/style/less/g3w-queryresults.less
  src/assets/style/less/g3w-sidebar.less
  src/assets/style/less/g3w-viewport.less
  src/components/CatalogChangeMapThemes.vue
  src/components/CatalogLayerLegend.vue
  src/components/CatalogTristateTree.vue
  src/components/FormHeader.vue
  src/components/GlobalTabsNode.vue
  src/components/InputTextHtml.vue
  src/components/QueryResults.vue
  src/components/Relation.vue
  src/components/Relations.vue
  src/components/RelationsPage.vue
  src/components/Viewport.vue
  src/components/WMS.vue
  src/components/index.js
  src/locales/de.js
  src/locales/en.js
  src/locales/fi.js
  src/locales/fr.js
  src/locales/it.js
  src/locales/ro.js
  src/locales/se.js
  src/services/viewport.js
Labels: feature

#285 Fix issue on GetFeatureInfo on initial not visible feature categories of layer
  src/app/core/layers/providers/wmsprovider.js
Labels: bug

#287 Fix issue on autocomplete search input with dependence
  src/app/gui/search/vue/panel/searchservice.js
  src/components/SearchPanel.vue
  src/components/SearchSelect2.vue
Labels: bug

#273 Improve how to develop instructions within `README.md`
  README.md
Labels: docs

#210 Update `"isMobile"` dependency to v1.1.1
  src/assets/vendors/ismobile/ismobile.min.js
Labels: dependencies

#286 Replace `improve_documentation.yml` with `config.yml`
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/improve_documentation.yml
Labels: github

#152 Remove deprecated npm scripts from `package.json` (`admin`, `default`, `plugins`)
  package.json
Labels: config

#221 Overall rename ambiguous variable name from `lng` to `language`
  src/app/config.js
  src/app/core/i18n/i18n.service.js
  src/app/g3w-ol/controls/geocodingcontrol.js
  src/app/gui/inputs/input.js
  src/app/main.js
  src/components/App.vue
  src/components/GlobalDateTime.vue
  src/components/QueryResultsActionQueryPolygonCSVAttributes.vue
  src/components/SearchDatetime.vue
  src/directives/v-t-html.js
  src/directives/v-t-placeholder.js
  src/directives/v-t-plugin.js
  src/directives/v-t-title.js
  src/directives/v-t-tooltip.js
  src/directives/v-t.js
  src/services/application.js
  src/store/application-state.js
Labels: refactoring

#170 Gracefully handle error/info messages from api request server (show to end user error notice details)
  src/app/core/errors/parser/servererrorparser.js
Labels: ux

#304 Fix catalog layers context submenu (change color on external layers) being clipped from the bottom of the page
  src/components/CatalogLayerContextMenu.vue
Labels: bug

#298 Deprecate function `QueryResultsService::addRemoveFeaturesToLayerResult(layer)`
  src/app/gui/queryresults/queryresultsservice.js
Labels: refactoring

#302 Install `vue-color` and `vue-cookie` as ESM packages
  gulpfile.js
  package.json
  src/app/main.js
  src/assets/vendors/vue-color/vue-color.js
  src/assets/vendors/vue-color/vue-color.js.map
  src/assets/vendors/vue-color/vue-color.min.js
  src/assets/vendors/vue/cookie/vue-cookie.js
  src/components/CatalogLayerContextMenu.vue
  src/components/MapAddLayer.vue
  src/deprecated.js
  test/config/vendors.js
Labels: dependencies

#307 Keep initial legend item state (expandend/collapsed) as per QGIS project
  src/app/core/layers/geolayermixin.js
  src/app/core/layers/layersstore.js
  src/components/CatalogLayerLegend.vue
  src/components/CatalogTristateTree.vue
Labels: bug

#315 Get Legend request only when Legend Layers is on SEPARATE TAB and is active
  src/components/CatalogLayersLegendItems.vue
Labels: bug
