Repository g3w-suite/g3w-client, pull requests merged in 2023-04, with the labels that each got.

#400 Dynamically update features count after manually switching layer category style (ref: layers legend)
  src/app/core/layers/layer.js
  src/app/core/project/project.js
  src/components/CatalogLayerContextMenu.vue
  src/components/CatalogLayerLegend.vue
Labels: feature

#398 List all MacroGroups, Groups and Projects within Change Map results (ref: top navbar menu)
  src/app/constant.js
  src/app/core/layers/layer.js
  src/app/gui/changemapmenu/changemapmenu.js
  src/app/gui/map/mapservice.js
  src/components/App.vue
  src/components/CatalogLayerLegend.vue
  src/components/CatalogTristateTree.vue
  src/components/ChangeMapMenu.vue
  src/components/InputDateTimePicker.vue
  src/components/index.js
  src/index.prod.js
  src/locales/de.js
  src/locales/en.js
  src/locales/fi.js
  src/locales/fr.js
  src/locales/it.js
  src/locales/ro.js
  src/locales/se.js
  src/services/application.js
  src/store/projects.js
Labels: feature

#403 Review and refactor pull request #398
  src/app/constant.js
  src/app/core/layers/layer.js
  src/app/g3w-ol/projection/projections.js
  src/app/gui/changemapmenu/changemapmenu.js
  src/app/gui/map/mapservice.js
  src/components/App.vue
  src/components/CatalogLayerLegend.vue
  src/components/CatalogTristateTree.vue
  src/components/ChangeMapMenu.vue
  src/components/InputDateTimePicker.vue
  src/components/index.js
  src/index.prod.js
  src/locales/de.js
  src/locales/en.js
  src/locales/fi.js
  src/locales/fr.js
  src/locales/it.js
  src/locales/ro.js
  src/locales/se.js
  src/services/application.js
Labels: refactoring

#349 Deprecate `src/app/core/g3w-ol/controls/utils.js`
  src/app/core/utils/ol.controls.js
  src/app/g3w-ol/controls/utils.js
Labels: refactoring

#310 Localize error page messages (ref: `Application::fail( { error } )`)
  src/app/gui/templates/500.html
  src/index.prod.js
  src/locales/de.js
  src/locales/en.js
  src/locales/fi.js
  src/locales/fr.js
  src/locales/it.js
  src/locales/ro.js
  src/locales/se.js
Labels: i18n

#390 Allow to print external WMS layers with same origin URL of application (ref: `"geoscreenshot"` and `"screenshot"` map controls)
  src/app/core/utils/utils.js
  src/app/g3w-ol/controls/screenshotcontrol.js
Labels: ux

#401 Allow to display server messages to end user on first page load (ref: modal dialog within `components/App.vue`)
  src/app/constant.js
  src/app/core/project/project.js
  src/app/gui/queryresults/queryresultsservice.js
  src/assets/style/less/app.less
  src/components/App.vue
  src/components/ChangeMapMenu.vue
  src/components/ProjectsMenu.vue
  src/index.prod.js
  src/locales/de.js
  src/locales/en.js
  src/locales/fi.js
  src/locales/fr.js
  src/locales/it.js
  src/locales/ro.js
  src/locales/se.js
  src/store/projects.js
Labels: feature
