Repository g3w-suite/g3w-client, pull requests merged in 2024-02, with the labels that each got.

#392 Add shortcut links within catalog layers context menu (layers and project settings)
  src/assets/style/less/g3w-catalog.less
  src/assets/style/less/g3w-skins/blue/g3w-catalog.less
  src/assets/style/less/g3w-skins/green/g3w-catalog.less
  src/assets/style/less/g3w-skins/purple/g3w-catalog.less
  src/assets/style/less/g3w-skins/red/g3w-catalog.less
  src/assets/style/less/g3w-skins/yellow/g3w-catalog.less
  src/components/Catalog.vue
  src/components/CatalogLayerContextMenu.vue
  src/components/CatalogProjectContextMenu.vue
  src/components/CatalogTristateTree.vue
  src/components/index.js
  src/directives/v-click-outside.js
  src/index.prod.js
Labels: feature

#561 Fix regression on conditional fields visibilty within form tab group
  src/components/GlobalTabs.vue
Labels: bug, backport to v3.9.x

#564 Ensure `filter_fields` is not null on relation reference widgets
  src/components/InputSelect.vue
Labels: bug, backport to v3.9.x

#566 Prevent `RequestNotWellFormed` error for invalid characters in BBOX requests (ref: layer names with spaces, colons or slashes)
  src/app/core/layers/imagelayer.js
  src/app/core/layers/layersstore.js
  src/app/g3w-ol/controls/querybydrawpolygoncontrol.js
  src/app/gui/queryresults/queryresultsservice.js
  src/components/QueryResults.vue
  src/utils/parsers/index.js
Labels: bug, backport to v3.9.x

#572 Delete `src/app/core/applicationservice.js`
  src/app/core/applicationservice.js
Labels: refactoring

#568 Delete `src/app/gui/charts/chartsfactory.js`
  src/app/api.js
  src/app/gui/charts/chartsfactory.js
Labels: refactoring

#573 Delete `src/app/core/relations/relations.js`
  src/app/core/layers/mixins/relations.js
  src/app/core/relations/relation.js
  src/app/core/relations/relations.js
Labels: refactoring

#571 Delete `src/app/core/project/projecttypes.js`
  src/app/core/project/projecttypes.js
Labels: refactoring

#570 Delete `src/app/gui/component/componentsfactory.js`
  src/app/api.js
  src/app/core/plugin/plugin.js
  src/app/gui/component/component.js
  src/app/gui/component/componentsfactory.js
Labels: refactoring

#485 Use a single `g3w-client/gulpfile.js` to compile all client plugins
  .gitignore
  README.md
  gulpfile.js
  package.json
  src/app/api.js
  src/app/core/plugin/plugin.js
  src/components/GlobalRange.vue
  src/components/LayerOpacityPicker.vue
  src/plugins/_version.js
  src/services/application.js
  src/store/application-state.js
  src/store/plugins.js
  src/version.js
Labels: docs, config

#578 Remove unnecessary branch name suffix for stable version releases
  gulpfile.js
  src/app/core/plugin/pluginservice.js
  src/plugins/_version.js
  src/store/plugins.js
Labels: config

#581 Fix regression: "catalog legend items stays grayed out"
  src/components/CatalogTristateTree.vue
Labels: bug

#583 Prevent "Uncaught TypeError: n.context[i.value][u] is undefined" when adding external WMS Layer
  src/components/WMSLayersPanel.vue
  src/directives/v-select2.js
Labels: bug, backport to v3.9.x

#579 Click to go back button to show MacroGroup list from Group page within `ChangeMapMenu.vue`
  src/components/ChangeMapMenu.vue
  src/components/Relation.vue
Labels: ux, backport to v3.9.x, backport to v3.8.x
