Repository g3w-suite/g3w-client, pull requests merged in 2024-08, with the labels that each got.

#649 Backport: #641 + some other minor UX improvements
  README.md
  package.json
  src/app/constant.js
  src/app/core/layers/features/featuresstore.js
  src/app/core/layers/features/olfeaturesstore.js
  src/app/gui/fields/fields.js
  src/app/gui/fields/fieldsservice.js
  src/app/gui/form/formservice.js
  src/app/gui/inputs/checkbox/service.js
  src/app/gui/inputs/datetimepicker/service.js
  src/app/gui/inputs/float/service.js
  src/app/gui/inputs/input.js
  src/app/gui/inputs/inputs.js
  src/app/gui/inputs/integer/service.js
  src/app/gui/inputs/lonlat/service.js
  src/app/gui/inputs/media/service.js
  src/app/gui/inputs/picklayer/service.js
  src/app/gui/inputs/radio/service.js
  src/app/gui/inputs/range/service.js
  src/app/gui/inputs/select/service.js
  src/app/gui/inputs/service.js
  src/app/gui/inputs/services.js
  src/app/gui/inputs/sliderrange/service.js
  src/app/gui/inputs/unique/service.js
  src/app/gui/map/mapservice.js
  src/assets/style/less/app.less
  src/components/QueryResults.vue
  src/components/Relation.vue
  src/components/SearchPanel.vue
  src/utils/getDataForSearchInput.js
  src/utils/reverseGeometry.js
  src/version.js
Labels: bug

#652 Missing form autocompletion when default print template is "Atlas"
  src/components/Print.vue
Labels: bug, backport to v3.10.x

#654 Update french translations
  src/locales/fr.js
Labels: i18n, backport to v3.8.x

#541 Refactor response parsers (aka. MIME Types)
  src/app/api.js
  src/app/core/errors/parser/servererrorparser.js
  src/app/core/layers/providersfactory.js
  src/app/g3w-ol/controls/querycontrol.js
  src/app/gui/map/mapservice.js
  src/app/gui/queryresults/queryresultsservice.js
  src/components/QueryResultsActionInfoFormats.vue
  src/utils/handleQueryResponse.js
  src/utils/parsers/index.js
Labels: refactoring
