Repository g3w-suite/g3w-client, pull requests merged in 2024-01, with the labels that each got.

#536 Fix empty query results for external WMS layers
  src/app/gui/queryresults/queryresultsservice.js
  src/components/MapAddLayer.vue
  src/components/QueryResults.vue
  src/components/QueryResultsActionInfoFormats.vue
  src/utils/parsers/index.js
Labels: bug

#533 Deprecate class attributes: `QueryResultsService~printService` and `PrintComponentService~printService`
  src/app/core/print/printservice.js
  src/app/gui/print/printservice.js
  src/app/gui/print/vue/print.js
  src/app/gui/print/vue/printpage.js
  src/app/gui/queryresults/queryresultsservice.js
Labels: refactoring

#534 Add support for `chain filter` option within relation reference widget [g3w-client-plugin-editing#63]
  src/app/core/layers/layer.js
  src/app/core/layers/providersfactory.js
  src/components/InputSelect.vue
  src/directives/v-select2.js
  src/mixins/base-input.js
Labels: feature

#531 Fix invalid `FORMAT` parameter for external WMS layers
  src/app/core/layers/baselayer.js
  src/app/core/layers/geojson.js
  src/app/core/layers/imagelayer.js
  src/app/core/layers/layer.js
  src/app/core/layers/layersstore.js
  src/app/core/layers/layersstoresregistry.js
  src/app/core/layers/map/arcgismapserverlayer.js
  src/app/core/layers/map/geojson.js
  src/app/core/layers/map/maplayer.js
  src/app/core/layers/map/vectorlayer.js
  src/app/core/layers/map/wmslayer.js
  src/app/core/layers/map/wmstlayer.js
  src/app/core/layers/map/wmtslayer.js
  src/app/core/layers/map/xyzlayer.js
  src/app/core/layers/mixins/geo.js
  src/app/core/layers/providersfactory.js
  src/app/core/layers/vectorlayer.js
  src/app/g3w-ol/layers/rasters.js
  src/app/gui/map/mapservice.js
  src/utils/geo/index.js
  src/utils/getMapLayerById.js
  src/utils/getMapLayersByFilter.js
  src/utils/get_legend_params.js
Labels: bug

#526 Handle deep relations on editing [g3w-admin#PR685]
  src/app/core/editing/editor.js
  src/app/core/editing/history.js
  src/app/core/editing/session.js
  src/components/Relation.vue
  src/store/plugins.js
Labels: bug

#493 Remove API `g3wsdk.core.editing` related to `g3w-client-plugin-editing` repository
  src/app/api.js
  src/app/constant.js
  src/app/core/editing/editor.js
  src/app/core/editing/history.js
  src/app/core/editing/session.js
  src/app/core/layers/tablelayer.js
  src/services/editing.js
  src/store/index.js
  src/store/sessions.js
Labels: refactoring

#544 Update version check within `config.template.js`
  config.template.js
Labels: config

#542 Delete file: `src/utils/ol/index.js`
  src/app/api.js
  src/app/constant.js
  src/app/core/layers/mixins/geo.js
  src/app/core/layers/providersfactory.js
  src/app/g3w-ol/controls/areacontrol.js
  src/app/g3w-ol/controls/basequerypolygoncontrol.js
  src/app/g3w-ol/controls/lengthcontrol.js
  src/app/g3w-ol/controls/querycontrol.js
  src/app/g3w-ol/controls/resetcontrol.js
  src/app/g3w-ol/controls/scalecontrol.js
  src/app/g3w-ol/controls/streetviewcontrol.js
  src/app/g3w-ol/interactions/measureinteraction.js
  src/app/g3w-ol/layers/rasters.js
  src/app/gui/map/mapservice.js
  src/app/gui/print/printservice.js
  src/utils/createMeasureTooltip.js
  src/utils/createPolygonLayerFromBBox.js
  src/utils/formatMeasure.js
  src/utils/getAreaMessageText.js
  src/utils/getCurrentMapUnit.js
  src/utils/getDPI.js
  src/utils/getExtentForViewAndSize.js
  src/utils/getLengthMessageText.js
  src/utils/getMetersFromDegrees.js
  src/utils/getResolutionFromScale.js
  src/utils/getScaleFromResolution.js
  src/utils/mergeOptions.js
  src/utils/needUseSphereMethods.js
  src/utils/ol/index.js
  src/utils/parsers/index.js
  src/utils/removeMeasureTooltip.js
  src/utils/reverseGeometry.js
  src/utils/setMeasureTooltipStatic.js
  src/utils/transformMeterArea.js
  src/utils/transformMeterLength.js
Labels: refactoring

#545 Remove API `g3wsdk.core.workflow` related to `g3w-client-plugin-editing` repository
  src/app/api.js
  src/app/core/workflow/flow.js
  src/app/core/workflow/queque.js
  src/app/core/workflow/step.js
  src/app/core/workflow/task.js
  src/app/core/workflow/workflow.js
  src/components/UserMessageSteps.js
  src/components/index.js
  src/locales/de.js
  src/locales/en.js
  src/locales/fi.js
  src/locales/fr.js
  src/locales/it.js
  src/locales/ro.js
  src/locales/se.js
  src/services/application.js
  src/services/index.js
  src/services/workflows.js
Labels: refactoring

#550 Wrong import uniqueId method
  src/utils/geo/index.js
Labels: bug

#557 Add `.github/workflows/backport.yml`
  .github/workflows/backport.yml
Labels: github

#555 Fix invalid geocoding response for `"X,Y,EPSG"` searches, i.e. those with a different CRS than the current map
  src/components/MapControlGeocoding.vue
Labels: bug, backport v3.9.x

#552 Ensure switching layer legend styles change after changing map theme
  src/app/core/layers/layer.js
  src/components/Catalog.vue
  src/components/CatalogLayerLegend.vue
Labels: bug, backport v3.9.x
