Repository g3w-suite/g3w-client, pull requests merged in 2024-10, with the labels that each got.

#666 Refactor query response
  src/components/Catalog.vue
  src/components/MapControlGeocoding.vue
  src/components/QueryResults.vue
  src/components/QueryResultsActionInfoFormats.vue
  src/services/gui.js
  src/services/queryresults.js
Labels: refactoring

#52 Update `package.json` (remove unusued gulp plugins)
  gulpfile.js
  package.json
Labels: dependencies

#673 Handle selection of multi values on input widget value relation
  src/components/InputSelect.vue
  src/components/SearchPanel.vue
  src/map/layers/tablelayer.js
  src/services/queryresults.js
  src/utils/getFilterExpression.js
Labels: feature

#675 :sparkles: Show Label in checkbox widget
  src/app/gui/inputs/checkbox/service.js
  src/components/InputCheckbox.vue
  src/mixins/index.js
  src/mixins/widget.js
Labels: feature

#674 :sparkles: Editing layer visible status
  src/map/layers/tablelayer.js
  src/services/queryresults.js
Labels: feature
