Repository g3w-suite/g3w-client, pull requests merged in 2025-03, with the labels that each got.

#750 Ukrainian translation
  src/locales/index.js
  src/locales/uk.js
Labels: i18n

#752 🐛 Get editing features
  src/map/layers/layer.js
Labels: bug, backport to v3.11.x

#754 Show a warning message to user in case of server error (user themes API)
  src/components/CatalogChangeMapThemes.vue
Labels: ux, backport to v3.11.x

#755 🔙 from #754
  src/components/CatalogChangeMapThemes.vue
Labels: bug

#758 Prevent copying static assets from `g3w-admin-*` plugins (`npm run build`)
  gulpfile.js
Labels: config

#760 Add css variable `--bgcolor`
  README.md
  src/assets/app.css
  src/components/App.vue
  src/components/Catalog.vue
  src/components/CatalogChangeMapThemes.vue
  src/components/CatalogContextMenu.vue
  src/components/GlobalHelpDiv.vue
  src/components/GlobalTabs.vue
  src/components/GlobalTabsNode.vue
  src/components/InputBase.vue
  src/components/InputCheckbox.vue
  src/components/InputRadio.vue
  src/components/Map.vue
  src/components/ModalAddLayer.vue
  src/components/ModalMetadata.vue
  src/components/Print.vue
  src/components/SearchPanel.vue
  src/components/Table.vue
  src/services/queryresults.js
Labels: ux

#757 Add `g3w` data provider and refactor `queryby` (area) map control
  src/components/GlobalTabs.vue
  src/components/ModalAddLayer.vue
  src/components/QueryBuilder.vue
  src/locales/en.js
  src/locales/it.js
  src/locales/uk.js
  src/map/controls/interactioncontrol.js
  src/map/controls/queryby.js
  src/map/layers/layer.js
  src/services/data.js
Labels: refactoring, backport to v3.11.x

#767 🐛 Zoom to feature when Projection has inverted axis [ex. EPSG:4326]
  src/utils/parsers/index.js
Labels: bug, backport to v3.11.x

#765 🔙 from #757
  src/components/GlobalTabs.vue
  src/components/ModalAddLayer.vue
  src/components/QueryBuilder.vue
  src/locales/en.js
  src/locales/it.js
  src/locales/uk.js
  src/map/controls/interactioncontrol.js
  src/map/controls/queryby.js
  src/map/layers/layer.js
  src/services/data.js
Labels: refactoring

#762 Ensure sending `ordering` parameter to server only after user click has clicked on a column (table pagination)
  src/components/Relation.vue
Labels: ux, backport to v3.11.x

#769 🔙 from #762 - Ensure sending ordering parameter to server only after user click has clicked on a column (table pagination)
  src/components/Relation.vue
Labels: bug
