Repository g3w-suite/g3w-client, pull requests merged in 2025-08, with the labels that each got.

#839 Search option "Alternative Unique Level" not honored when field is first in config
  src/components/g3w-search.js
Labels: bug, backport to v4.0.x

#841 Conditionally show form labels (query, search and editing)
  src/components/Field.vue
  src/components/GlobalTabsNode.vue
  src/components/InputBase.vue
  src/map/layers/layer.js
Labels: feature, backport to v4.0.x

#844 Pagination controls on multi layers search is shown on wrong layers when any of them got no response
  src/components/QueryResults.vue
  src/services/data.js
Labels: bug
