Repository g3w-suite/g3w-client, pull requests merged in 2025-07, with the labels that each got.

#817 Simplify mobile menu (top/left sidebar)
  src/assets/app.css
  src/components/App.vue
  src/components/Catalog.vue
  src/components/CatalogContextMenu.vue
  src/components/SpatialBookMarks.vue
  src/map/controls/geocoding.js
  src/services/gui.js
Labels: ux

#822 Unable to switch base layer when current project contains a Bing base layer without a vendorkey
  src/utils/getProject.js
Labels: bug

#824 Unable to load external layers with EPSGs unregistered for current project
  src/components/ModalAddLayer.vue
Labels: bug

#825 Vue i18n reactivity
  src/components/App.vue
  src/g3w-i18n.js
  src/g3w-plugin.js
  src/index.prod.js
  src/map/controls/zoombox.js
  src/map/controls/zoomtoextent.js
Labels: i18n

#827 Rename class function: `QueryResultsService~trigger()` → `QueryResultsService~triggerAction()`
  src/components/QueryResults.vue
  src/services/queryresults.js
Labels: refactoring

#829 ⬆️ Bump `"ol"` from 10.4.0 to 10.6.1 and `"proj4"` from 2.14.0 to 2.19.6
  package.json
Labels: dependencies

#821 Add Bulgarian translation
  src/assets/locales/bg.js
  src/assets/locales/index.js
  src/assets/locales/it.js
  src/components/ModalChangeMap.vue
Labels: i18n

#836 Sidebar toggler overlaps geocoding control when application runs within an iframe
  src/components/App.vue
  src/map/controls/geocoding.js
Labels: ux, backport to v4.0.x
