Repository g3w-suite/g3w-client, pull requests merged in 2025-02, with the labels that each got.

#705 Add pagination on relation table on query/search result container
  src/components/Relation.vue
  src/components/RelationsPage.vue
  src/services/queryresults.js
  src/utils/createRelationsUrl.js
Labels: feature, backport to v3.11.x

#708 🔙 from #704 - Ensure unique IDs for modal galleries
  src/components/FieldImage.vue
Labels: bug

#709 Add support for `LAYERFONTSIZE`, `ITEMFONTSIZE` and `SHOWFEATURECOUNT` parameters (rif: `GetLegendGraphic`)
  src/components/Catalog.vue
  src/map/layers/imagelayer.js
Labels: feature, backport to v3.11.x

#714 :bug: Get legend from wms layer through internal qgisserver if set internal
  src/components/Catalog.vue
  src/map/layers/imagelayer.js
Labels: bug, backport to v3.11.x

#717 Street view not visible on subsequent map click
  src/services/gui.js
Labels: bug, backport to v3.11.x

#719 Failsafe delete plugins `package.json` cache
  gulpfile.js
Labels: config

#725 Always emit `plugin.js` into plugin repository
  gulpfile.js
Labels: config, backport to v3.11.x

#726 :bug: Fix call to undefind method `zoomToExtent` (BaseIframeService)
  src/services/iframe.js
Labels: bug, backport to v3.11.x

#728 🔙 from #725 - Always emit `plugin.js` into plugin repository
  gulpfile.js
Labels: config

#712 Allow to customize close tooltip text (sidebar panel)
  src/components/App.vue
  src/components/QueryBuilder.vue
  src/store/application.js
Labels: feature, backport to v3.11.x

#697 Adds Portuguese translation
  src/locales/index.js
  src/locales/pt.js
Labels: i18n, backport to v3.11.x

#734 :bug: Confirm to generate screenshot (iframe modal)
  src/map/controls/screenshotcontrol.js
  src/services/iframe.js
Labels: bug, backport to v3.11.x

#737 :bug: Prevent registering invalid `proj4.defs`
  src/store/projections.js
Labels: bug

#736 :bug: Editing panel doesn't open for more than one layer (edit in iframe)
  config.template.js
  src/index.dev.js
  src/services/iframe.js
Labels: bug, backport to v3.11.x

#738 🔙 #736 - Editing panel doesn't open for more than one layer (edit in iframe)
  config.template.js
  src/index.dev.js
  src/services/iframe.js
Labels: bug

#743 🐛 Download layer features from search with pagination
  src/components/QueryResults.vue
  src/services/queryresults.js
Labels: bug, backport to v3.11.x

#742 🐛 Repeated values found on multi search layers with the same value of a select input
  src/utils/getDataForSearchInput.js
Labels: bug, backport to v3.11.x
