Repository g3w-suite/g3w-client, pull requests merged in 2025-04, with the labels that each got.

#764 🐛 Missing `FORMAT` parameter in server requests (WMS GetMap image format)
  src/services/map.js
Labels: bug, backport to v3.11.x

#756 Allow user whether to download layer with relations
  src/assets/app.css
  src/components/CatalogContextMenu.vue
  src/components/QueryResults.vue
  src/components/QueryResultsActionDownloadFormats.vue
  src/locales/de.js
  src/locales/en.js
  src/locales/fi.js
  src/locales/fr.js
  src/locales/it.js
  src/locales/pl.js
  src/locales/pt.js
  src/locales/ro.js
  src/locales/se.js
  src/locales/uk.js
  src/map/layers/layer.js
  src/services/queryresults.js
Labels: feature, backport to v3.11.x

#739 Custom query result action button: “Update feature in iframe” (ref: `index.dev.js`)
  src/index.dev.js
Labels: tests

#774 Filter selection on query area control + saving of forms with fields with a default expression (without dependencies)
  src/components/QueryResults.vue
  src/components/QueryResultsHeaderFeatureBody.vue
  src/components/g3w-form.js
  src/map/layers/layer.js
  src/services/queryresults.js
  src/utils/parsers/index.js
Labels: bug, backport to v3.11.x

#777 Prevent feature ID collision when selecting features from multiple layers
  src/map/layers/geo-mixin.js
Labels: bug, backport to v3.11.x

#779 Remove `src/index.html`
  gulpfile.js
  src/index.html
Labels: config

#785 Missing "active filter" warning within search panel (layer with relations)
  src/assets/app.css
  src/components/QueryResults.vue
  src/components/Search.vue
  src/components/SearchPanel.vue
  src/components/Table.vue
  src/components/g3w-search.js
  src/index.dev.js
  src/locales/en.js
  src/locales/it.js
  src/map/layers/layer.js
  src/services/queryresults.js
  src/utils/getDataForSearchInput.js
  src/utils/getRelationLayerById.js
Labels: bug, backport to v3.11.x

#786 🔙 from #785 - Missing "active filter" warning within search panel (layer with relations)
  src/assets/app.css
  src/components/QueryResults.vue
  src/components/Search.vue
  src/components/SearchPanel.vue
  src/components/Table.vue
  src/components/g3w-search.js
  src/index.dev.js
  src/locales/en.js
  src/locales/it.js
  src/map/layers/layer.js
  src/services/queryresults.js
  src/utils/getDataForSearchInput.js
  src/utils/getRelationLayerById.js
Labels: bug

#782 Allow to specify `G3WObject~setters` property as an array of strings
  src/components/g3w-form.js
  src/g3w-object.js
  src/map/layers/featuresstore.js
  src/map/layers/imagelayer.js
  src/map/layers/layersstore.js
  src/map/layers/tablelayer.js
  src/services/gui.js
  src/services/map.js
  src/services/queryresults.js
Labels: refactoring

#771 ✨ Allow users to search/filter relation table columns
  src/components/Field.vue
  src/components/Relation.vue
  src/map/layers/layer.js
  src/utils/createRelationsUrl.js
Labels: feature
