Repository g3w-suite/g3w-client, pull requests merged in 2025-06, with the labels that each got.

#810 Unable to download feature after opening attribute table
  src/services/data.js
  src/services/queryresults.js
Labels: bug, backport to v3.11.x

#815 Remove `"show-plots-relations"` layers action from core
  package.json
  src/assets/app.css
  src/components/App.vue
  src/components/CatalogContextMenu.vue
  src/components/ModalLogin.vue
  src/components/QueryResults.vue
  src/components/QueryResultsAction.vue
  src/components/Relation.vue
  src/directives/v-select2.js
  src/directives/v-t-html.js
  src/directives/v-t-plugin.js
  src/directives/v-t-tooltip.js
  src/directives/v-t.js
  src/g3w-i18n.js
  src/g3w-vendors.js
  src/index.prod.js
  src/map/controls/geocoding.js
  src/map/controls/zoomhistory.js
  src/map/layers/layer.js
  src/services/gui.js
  src/services/queryresults.js
Labels: refactoring

#814 Management of Max and Min scales by layer's styles [PR 1138 admin]
  src/components/CatalogTristateTree.vue
  src/map/layers/imagelayer.js
  src/map/layers/layer.js
Labels: feature
