Repository g3w-suite/g3w-client, pull requests merged in 2025-05, with the labels that each got.

#792 🐛Change features number for page in pagination
  src/components/CatalogContextMenu.vue
  src/components/CatalogLayerLegend.vue
  src/components/QueryResults.vue
  src/g3w-vendors.js
  src/map/layers/layer.js
  src/services/map.js
  src/services/queryresults.js
  src/utils/parsers/index.js
Labels: bug

#793 ✨ Handle specific editing layer style for editing
  src/components/CatalogContextMenu.vue
  src/components/CatalogLayerLegend.vue
  src/components/Relation.vue
  src/map/layers/layer.js
  src/map/layers/tablelayer.js
  src/utils/getProject.js
Labels: feature

#799 Filter legend by map content
  src/components/Catalog.vue
  src/map/layers/imagelayer.js
  src/services/map.js
Labels: bug, backport to v3.11.x

#800 🔙 from #799 - Filter legend by map content
  src/components/Catalog.vue
  src/services/map.js
Labels: bug

#796 ✨ Show preview image
  src/assets/app.css
  src/components/FieldImage.vue
  src/components/QueryResultsHeaderFeatureBody.vue
Labels: ux

#791 Add new map control: `"annotation"`
  package.json
  src/assets/app.css
  src/assets/images/controls/mActionAddBasicCircle.svg
  src/assets/images/controls/mActionAddBasicRectangle.svg
  src/assets/images/controls/mActionAddPoint.svg
  src/assets/images/controls/mActionAddPolygon.svg
  src/assets/images/controls/mActionAddPolyline.svg
  src/assets/images/controls/mActionCreateAnnotationLayer.svg
  src/assets/images/controls/mActionText.svg
  src/assets/images/controls/mActionTextAnnotation.svg
  src/components/Map.vue
  src/g3w-constants.js
  src/g3w-globals.js
  src/index.dev.js
  src/locales/en.js
  src/locales/it.js
  src/map/controls/annotationcontrol.js
  src/map/controls/interactioncontrol.js
  src/map/controls/measurecontrol.js
  src/services/map.js
  src/utils/createMeasureTooltip.js
  src/utils/removeMeasureTooltip.js
Labels: feature

#797 Limit number of fields displayed within query results preview (per layer)
  src/components/QueryResults.vue
  src/map/layers/layer.js
  src/services/queryresults.js
Labels: feature

#802 Recallable Messages/Info
  src/assets/app.css
  src/components/App.vue
  src/components/CatalogChangeMapThemes.vue
  src/components/InputCheckbox.vue
  src/components/InputRadio.vue
  src/components/SearchPanel.vue
  src/components/SpatialBookMarks.vue
  src/components/Table.vue
  src/components/g3w-alerts.js
  src/g3w-constants.js
  src/index.prod.js
  src/locales/en.js
  src/locales/it.js
  src/services/gui.js
  src/services/queryresults.js
Labels: feature

#808 🔙 from #804 - Handle layer selection/filter on paginated tables + search results with autofilter
  src/components/Table.vue
  src/map/layers/layer.js
  src/services/map.js
  src/services/queryresults.js
Labels: bug
